/*
 * Emit DBOPL's two floating-point tables as C, so the firmware does not compute
 * them at boot.
 *
 * DBOPL::InitTables() builds six tables. Four are integer arithmetic and cost
 * nothing; two are not, and between them they are the only reason the firmware
 * links pow() and sin() at all - and they occupy 8,960 bytes of .bss holding
 * values that are identical on every boot. This program computes them once, on
 * the host, where a maths library is free.
 *
 * The expressions below are copied verbatim from dbopl.cpp, loops and casts
 * included, so there is no translation step to get subtly wrong. When that file
 * changes, this one has to change with it - which is what the dbopl-tables host
 * test is for: it runs both and compares element by element.
 *
 * Only the DBOPL_WAVE == WAVE_TABLEMUL forms are here, because that is the mode
 * dbopl.h selects. The WAVE_HANDLER and WAVE_TABLELOG branches build ExpTable
 * and SinTable instead and are not compiled.
 */
#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include <string.h>

#define PI      3.14159265358979323846   /* dbopl.cpp:64  */
#define MUL_SH  16                       /* dbopl.cpp:118 */

static uint16_t MulTable[384];
static int16_t  WaveTable[8 * 512];

static void build(void)
{
	/* --- dbopl.cpp:1399, "Multiplication based tables" --- */
	for ( int i = 0; i < 384; i++ ) {
		int s = i * 8;
		double val = ( 0.5 + ( pow(2.0, -1.0 + ( 255 - s) * ( 1.0 /256 ) )) * ( 1 << MUL_SH ));
		MulTable[i] = (uint16_t)(val);
	}

	/* --- dbopl.cpp:1406, "Sine Wave Base" --- */
	for ( int i = 0; i < 512; i++ ) {
		WaveTable[ 0x0200 + i ] = (int16_t)(sin( (i + 0.5) * (PI / 512.0) ) * 4084);
		WaveTable[ 0x0000 + i ] = -WaveTable[ 0x200 + i ];
	}
	/* --- dbopl.cpp:1411, "Exponential wave" --- */
	for ( int i = 0; i < 256; i++ ) {
		WaveTable[ 0x700 + i ] = (int16_t)( 0.5 + ( pow(2.0, -1.0 + ( 255 - i * 8) * ( 1.0 /256 ) ) ) * 4085 );
		WaveTable[ 0x6ff - i ] = -WaveTable[ 0x700 + i ];
	}

	/* --- dbopl.cpp:1437, the silence gaps and the replicated sines --- */
	for ( int i = 0; i < 256; i++ ) {
		WaveTable[ 0x400 + i ] = WaveTable[0];
		WaveTable[ 0x500 + i ] = WaveTable[0];
		WaveTable[ 0x900 + i ] = WaveTable[0];
		WaveTable[ 0xc00 + i ] = WaveTable[0];
		WaveTable[ 0xd00 + i ] = WaveTable[0];
		WaveTable[ 0x800 + i ] = WaveTable[ 0x200 + i ];
		WaveTable[ 0xa00 + i ] = WaveTable[ 0x200 + i * 2 ];
		WaveTable[ 0xb00 + i ] = WaveTable[ 0x000 + i * 2 ];
		WaveTable[ 0xe00 + i ] = WaveTable[ 0x200 + i * 2 ];
		WaveTable[ 0xf00 + i ] = WaveTable[ 0x200 + i * 2 ];
	}
}

#ifdef DBOPL_TABLES_AS_LIBRARY

/* The host test links this instead of running main(), so it can compare these
 * against what dbopl.cpp computes at runtime. */
void dbopl_tables_reference(uint16_t *mul, int16_t *wave)
{
	build();
	memcpy(mul,  MulTable,  sizeof MulTable);
	memcpy(wave, WaveTable, sizeof WaveTable);
}

#else

static void emit_u16(const char *name, const uint16_t *t, int n)
{
	printf("static const uint16_t %s[%d] = {", name, n);
	for (int i = 0; i < n; i++)
		printf("%s%5u,", (i % 12) ? " " : "\n\t", t[i]);
	printf("\n};\n\n");
}

static void emit_i16(const char *name, const int16_t *t, int n)
{
	printf("static const int16_t %s[%d] = {", name, n);
	for (int i = 0; i < n; i++)
		printf("%s%6d,", (i % 10) ? " " : "\n\t", t[i]);
	printf("\n};\n\n");
}

int main(void)
{
	build();
	printf("/*\n"
	       " * Generated by tools/assets/dbopl_tables.c - do not edit.\n"
	       " *\n"
	       " * DBOPL::InitTables()'s two floating-point tables, computed at build time so\n"
	       " * the firmware links no maths library and keeps %zu bytes of .bss free.\n"
	       " */\n\n",
	       sizeof MulTable + sizeof WaveTable);
	emit_u16("MulTableFlash",  MulTable,  384);
	emit_i16("WaveTableFlash", WaveTable, 8 * 512);
	return 0;
}

#endif
