/*
 * Emit the MIDI-note-to-OPL {block, F-number} table, so the firmware does not
 * compute it with powf() and log2f() on every note-on.
 *
 * midi.c turned a note into an OPL frequency like this:
 *
 *     float octaves_from_A4 = (param1 - 69 - 12 + midi_semitones_higher) / 12.0f;
 *     float frequency       = powf(2.0f, octaves_from_A4) * 440.0f;
 *     float f_number_float  = frequency * (float)(1 << 20) / 49716.0f;
 *     int block             = (int)(log2f(f_number_float) - 9) & 7;
 *     int f                 = ((int)f_number_float >> block) & 1023;
 *
 * Every one of those depends on a single integer. param1 is a MIDI note, 0..127;
 * midi_semitones_higher is an sbyte set from a SysEx event, -128..127. So the
 * whole calculation is a function of
 *
 *     semi = param1 - 81 + midi_semitones_higher,   -209 .. 173
 *
 * which is 383 values - a 766-byte table against two transcendental calls per
 * note-on. block is 3 bits and f is 10, so they pack into one uint16_t.
 *
 * The expressions are copied verbatim from midi.c so the table is what that code
 * computed, rounding included, rather than what the arithmetic ideally says. The
 * midi-fnum host test renders a tune each way and requires the WAVs to match.
 *
 * The full range is well defined: at semi = -209 the F-number is 0.053 and at
 * semi = 173 it is 2.03e8, so neither the log nor either integer cast is ever
 * handed zero, infinity or something out of int range.
 */
#include <stdio.h>
#include <stdint.h>
#include <math.h>

#define SEMI_MIN (-209)
#define SEMI_MAX  ( 173)
#define SEMI_N   (SEMI_MAX - SEMI_MIN + 1)

int main(void)
{
	printf("/*\n"
	       " * Generated by tools/assets/midi_fnum_table.c - do not edit.\n"
	       " *\n"
	       " * OPL {block, F-number} for every MIDI note and transposition, so that a\n"
	       " * note-on costs a table lookup instead of powf() and log2f().\n"
	       " * Index by (semi - MIDI_FNUM_SEMI_MIN); the value packs block << 10 | f.\n"
	       " */\n\n");
	printf("#define MIDI_FNUM_SEMI_MIN (%d)\n", SEMI_MIN);
	printf("#define MIDI_FNUM_SEMI_MAX (%d)\n\n", SEMI_MAX);
	printf("static const uint16_t midi_fnum_table[%d] = {", SEMI_N);

	for (int i = 0; i < SEMI_N; i++) {
		int semi = SEMI_MIN + i;

		float octaves_from_A4 = semi / 12.0f;
		float frequency = powf(2.0f, octaves_from_A4) * 440.0f;
		float f_number_float = frequency * (float)(1 << 20) / 49716.0f;
		int block = (int)(log2f(f_number_float) - 9) & 7;
		int f = ((int)f_number_float >> block) & 1023;

		printf("%s0x%04x,", (i % 12) ? " " : "\n\t",
		       (unsigned)((block << 10) | f));
	}
	printf("\n};\n");
	return 0;
}
